name: main-push

on:
  push:
    branches: [ main ]
    
jobs:
  do-something-test:
    runs-on: self-hosted
    environment: 
      name: test
    steps:
    - run: echo 'do something on test'
  do-something-live:
    runs-on: self-hosted
    needs: do-something-test
    environment: 
      name: live
    steps:
    - run: echo 'do something on live'
