name: main-pr

on:
  pull_request:
    branches: [ main ]
    
jobs:
  do-something-pr-test:
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
    - run: echo 'do something for PR on test'
  do-something-pr-live:
    runs-on: ubuntu-latest
    needs: do-something-test
    environment: 
      name: live
    steps:
    - run: echo 'do something for PR on live'
